### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by MysteryNull** [johnjaejunlee95/SA_ConvLSTM#1]
Thanks for your excellent work! In example, --batch 4  "cuda out of memory" ,
and I have to set the batch to be 1, then it runs, but the accuracy is low. 
How to solve this problem? Which GPU you use to train the model?  I would greatly appreciate it if you reply.

**Comment by johnjaejunlee95** [comment]
> Thanks for your excellent work! In example, --batch 4 "cuda out of memory" , and I have to set the batch to be 1, then it runs, but the accuracy is low. How to solve this problem? Which GPU you use to train the model? I would greatly appreciate it if you reply.

Firstly, thank you for visiting my GitHub repo.

Regarding your question about the accuracies obtained from ConvLSTM and SA_ConvLSTM models, could you please share the accuracies that you obtained?

Moreover, I utilized multiple GPUs, specifically 4 to 8 Quadro RTX 8000 GPUs. Since each training process uses 4 batches per GPU, adjusting the learning rate might be necessary if you are using a single GPU.
